branches:
  only:
    - master
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
rvm:
  - "1.9.2"
  - "1.9.3"
  - ruby-head
  - rbx-19mode
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: ./script/ci
